#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'Parse'
pod 'AFNetworking'
pod 'JGProgressHUD'
pod 'pop', '~> 1.0'
pod 'HMSegmentedControl', '~> 1.3.0'
pod 'SherginScrollableNavigationBar'
pod 'LTNavigationBar'
